services:

  php:
    image: orchestra:dev
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    container_name: 'orchestra-php-test'
    volumes:
      - ./:/app
    working_dir: /app
    env_file:
      - .env
      - .env.test
